Support generating ESM output
Setting `emitESM=true` in the generator's configuration will switch from
using `require` to `import` calls in the generated code.

I haven't been successful in actually using the ESM output. Bi-directional
relationships between models lead to circular dependencies in
`*WhereInput` and `*ListRelationFilter` and cause the following error at
start-up:

> ReferenceError: Cannot access 'FooWhereInput' before initialization
>     at file:///app/node_modules/@generated/type-graphql/resolvers/inputs/FooListRelationFilter.js:10:31

Regardless of ESM setting, create a package.json if generating into
node_modules. This makes sure that the generated code doesn't inherit a
parent package's `type`.